### ISSUE TITLE
Default system bezels not applying

### ISSUE THREAD

**Issue by Brandoskey** [thebezelproject/BezelProject-Windows#11]
I'm using retroarch 1.8.4 and for some reason the default system bezels are not getting applied to games without bezels. I've tried reinstalling the bezels multiple times, all the config files seem to point to the right areas and still no joy.

**Comment by thebezelproject** [comment]
Not sure why your core cfg file isn't being updated, but you should be able to manually address this buy starting up a core with a game running, hit F1 to get back into Retroarch, then manually select the default bezel you want, then save a content directory override.
