### ISSUE TITLE
Bezel scripts for PS Vita bug?

### ISSUE THREAD

**Issue by lamvuong2019** [thebezelproject/BezelProject-Windows#12]
Just for testing I used the nes pack.

I downloaded everything fine and the overlay and config files were placed automatically into the right folder ux0:/data/retroarch/
The game I tested was 10-Yard Fight (USA, Europe) seems the bezzels are there however the config is wrong?

Orginal config:

overlays = 1
overlay0_overlay = :/overlays/GameBezels/NES/10-Yard_Fight_(USA,_Europe).png
overlay0_full_screen = true
overlay0_descs = 0

Modded config: overlays = 1
overlay0_overlay = 10-Yard_Fight_(USA,_Europe).png
overlay0_full_screen = true
overlay0_descs = 0

I am not sure where or what needs to be change for this to work correctly.

**Comment by thebezelproject** [comment]
It appears a number of older repos had an old path the code wasn't expecting. I have updated everything to current standards.
