### ISSUE TITLE
Cannot find archive

### ISSUE THREAD

**Issue by grizzer7878** [thebezelproject/BezelProject-Windows#14]
Hi,

I have been banging my head against the wall about this issue and I am hoping someone cant point out what I am overlooking. 

I keep receiving a Cannot Find Archive error from 7zip every time I try and download any bezel pack (doesn't matter which one). I've tried it with manual set to no and yes. I'll watch the zip show up in the temp folder while it's downloading and then it will throw the error. Ive whitelisted BP in anti virus and made firewall exceptions but nothing seems to work.

Any guidance would be much appreciated

**Comment by thebezelproject** [comment]
I assume you are using the latest version of the windows app?

**Comment by grizzer7878** [comment]
Yes, I'm using V 1.1.6 installed on an internal game drive (not my C drive). Ive actually tried several different versions of BP and installed in a few different locations. But I get the same error everytime. Having issues through several different version as well as me finding very few references to this error online make me think this is something that I am doing wrong on my end.

I just dont know what.

**Comment by thebezelproject** [comment]
I'm game for some testing if you are.

Here are some points and steps.

For fully automatic operation, make sure the 'Manual Install' option under Preferences is set to 'No'.

I assume the issue exists no matter what Bezel style is selected in Preferences, Themed or System Art?

When you get the error from unzip, are you able to see the completed zip download in %Temp%? If so, are you able to open this zip with your archive app of choice and run a test on it to make sure it is complete and intact?

**Comment by grizzer7878** [comment]
OK...

I think I got it, sometimes you just need a little shove in the right direction. 

I set manual to no and selected system art. Chose Retroarch, then I chose Sega 32X and started downloading. It popped up in the temp folder as it was downloading. It finished downloading and I got the same 7zip *cannot find archive* ERROR. Before clicking OK on the error box I checked the zip that just downloaded.
It was the full file. I extracted it myself in the temp folder then hit OK on the *cannot find archive* box. It did it's business and installed everything as it is supposed to. If you hit OK on the ERROR box before unpacking the zip yourself the zip file disappears and it says it installs it but it really doesnt.

**Comment by thebezelproject** [comment]
Very strange, you should not have to do that. Everything continues to work here and with most other users. I'll keep an eye out for other reports on the Facebook group page. At least you have a work around. Please let us know if you figure anything else out.

**Comment by grizzer7878** [comment]
I thought it was very weird. 

But I'm glad we were able at least to get me on the path of some bezels. 
If I run into anything else or figure out what is going on that is causing the issue for me I'll be sure and let you know.

Thanks for your help and your quick response!

**Comment by arnould1** [comment]
I am having the very same issue. Where are you looking to find the zip that downloaded before you hit ok on the error message?? thank you EDIT: Just tried it for the 4th time and it took!?!? perhaps there was a download error?? anyway thank you for the great project!!
