### ISSUE TITLE
Infinite Lay files writing during installation 

### ISSUE THREAD

**Issue by DarkanParx** [thebezelproject/BezelProject-Windows#15]
Hi,

Thanks for this amazing tool! 

I'm running into an issue during installation of the bezels for mame. The software is installed on my system drive whilst my portable mame is on an external drive. During the automatic process everything goes well until the point where it creates lay files. It counts 2046 files, once it reaches 100% it keeps going infinitely, reaching more than 3000% at which point I stop the process through Task manager. The program obviously doesn't register the pack as "installed", even though all files seem to be there and the bezels are working.

**Comment by thebezelproject** [comment]
What version of MAME and the Windows app are you running? Have you performed an 'Update' within the app to get the latest ini files?

What version of Windows are you using? Do you have plenty of extra space in %Temp%?

I have tried recreating the issue here, but can't so far. I can install both the 'Themed' and 'System Art' bezel sets for native MAME as intended. Any and all info you can provide would be helpful.

**Comment by DarkanParx** [comment]
Hi,

I'm using Windows 10 Home, I did update the .ini files. My TEMP in on a separate partition F: and there's plenty of space. Software on C: and Mame on portable drive I:. I've made a viseo to show the issue here: [VIDEO](https://drive.google.com/open?id=1Bj5t18Vk2EBcZGwhk3nn66fUEa3vr02J)
Mame version .219 with .218 Merged Romset.

**Comment by thebezelproject** [comment]
Do you have the same issue with other Bezel sets like Atari 2600, Genesis, etc., for native MAME/Retroarch/RocketLauncher/etc.?

**Comment by DarkanParx** [comment]
Tried only Mame roms so far, will try now.

EDIT: Atari 2600 on Retroarch works perfectly, Atari 7800 too and Colecovision. N64 downloads and installs but the bezels don't show, even though the bezels are in the Game Bezels folder.

**Comment by thebezelproject** [comment]
I have released V1.1.8 which hopefully fixes the native MAME looping issue. Please let me know how you get along with it.

**Comment by DarkanParx** [comment]
Works like a charm! Thanks! 

P.s. I've checked also the issue regarding N64 that I mentioned in my previous comment, it is actually working, I was using a different core so I moved the files to the active core directory and it works as expected. (Did't read the info, my bad)

Thanks, great job!

**Comment by thebezelproject** [comment]
Great! Many thanks for the quick feedback.
