### ISSUE TITLE
n64 didnt work

### ISSUE THREAD

**Issue by aafneto** [thebezelproject/BezelProject-Windows#17]
update script, but still not working the n64 bezels.

**Comment by thebezelproject** [comment]
The most likely issue is the directory for the core we use under ...\retroarch\config does not match the core you are using in Retroarch itself. Try renaming the appropriate core name and see if that fixes it.

**Comment by aafneto** [comment]
sorry, i dindt get... what i need rename?! the core? the folder?!

**Comment by thebezelproject** [comment]
There should be a folder in your ...\retroarch\config folder called Mupen64Plus GLES2. Since there is more than one N64 core, you may be using a core that expects a different name.

**Comment by aafneto** [comment]
yeap.. i see that folder, and the only 2 cores for n64 are: (mupen64plus-next and mupen64plus-next GLES 3), so what i need to rename?! tha folder in "config", the name of the core?!

**Comment by aafneto** [comment]
oks.. i am using "mupen64plus_next_libreto" core, try rename the folder in config.. but have no sucess. ;
- mupen64plus - mupen64plus_next - mupen64plus next... all those options... 
- and for the last, try to rename the core name to "mupen64plus" and the folder with the same name.. and nothing :/ the roms have the same name of the files in config folder.

**Comment by thebezelproject** [comment]
What version of Retroarch are you running?

Try the name Mupen64Plus-Next OpenGL.

Dreamcast should just work. Are you using Themed or System Art type bezels in Preferences for Dreamcast?

**Comment by aafneto** [comment]
- install the 1.8.5 retroarch version, but "update" the .exe files to 1.8.4 because a problem with netplay.
-  this works fine "Mupen64Plus-Next OpenGL", change the name of the folder, and the name of the core...
- dreamcast was a problem with the roms name (my bad)... 

everything solved... thx...
