### ISSUE TITLE
SMS - overlay dimension

### ISSUE THREAD

**Issue by aafneto** [thebezelproject/BezelProject-Windows#18]
Hii everyone.
i am having problem with the SMS size of overlays, all games of this system was too big, and cut part of the game screen... i use same core of genesis.. but in that sys.. all its fine.

**Comment by thebezelproject** [comment]
The Mastersystem bezels were created to support an Aspect Ratio of 4:3. Is that what you are using? Please provide a couple of games and example pics so we can see what you are seeing. No issues are showing up here.
