### ISSUE TITLE
Download All

### ISSUE THREAD

**Issue by coolspot18** [thebezelproject/BezelProject-Windows#20]
Is there a way to download all rather than select each system one by one?

**Comment by thebezelproject** [comment]
Sure, multi-select from the selection list and click on OK.
![image](https://user-images.githubusercontent.com/36973318/89716889-dc19b380-d97e-11ea-92a1-d86b8f855103.png)

**Comment by coolspot18** [comment]
Sorry, I should have looked at the new version of Bezel Project Windows installer first ... I see "Prompt for Update / Uninstalls" is now an option, it was PITA previously to click YES to each platform.

I appreicate you responding nevertheless to this issue 👍
