### ISSUE TITLE
Native MAME 0.215 w/ Latest Installer (1.1.12) + LAY Files - Problem?

### ISSUE THREAD

**Issue by coolspot18** [thebezelproject/BezelProject-Windows#21]
Hi all,

I think the new installer is generating incorrect lay files for Native MAME.

Old lay files work file (Created in April 28th, 2020 - not sure which release of the installer):

```
<!-- bezel.lay -->
<mamelayout version="2">
<element name="bezel">
<image file="bezel.png" />
</element>
<view name="Bezel Artwork">
<bezel element="bezel">
<bounds left="0" top="0" right="16" bottom="9" />
</bezel>
<screen index="0">
<bounds left="2" top="0" right="14" bottom="9" />
</screen>
</view>
</mamelayout>
```

New lay (1.1.12) files seem to mix up width/height, etc. with left/right/top attributes, hence causes the bezel not to load:

```
<!-- bezel.lay -->
<mamelayout version="2">
<element name="bezel">
<image file="bezel.png" />
</element>
<view name="Bezel Artwork">
<bezel element="bezel">
<bounds left="0" top="0" right="16" bottom="9" />
</bezel>
<screen index="0">
<bounds left="2" top="0" width="12" height="9" />
</screen>
</view>
</mamelayout>
```

Last line is:`<bounds left="2" top="0" width="12" height="9" />` is the only difference between the two files, and according to MAME's documentation I think you're only supposed to use width/height/x/y OR left/right/top/bottom.

**Comment by coolspot18** [comment]
I updated the LAY files to use a consistent naming convention but the new bezels are all offset to the left in MAME. Not sure why.

**Comment by coolspot18** [comment]
New LAY files also have a different alignment - i.e. right="14" bottom="9" vs width="12" height="9", this seems to cause alignment issues with the emulator output and the bezel. Even after changing width/height to right/bottom, image is shifted.

**Comment by thebezelproject** [comment]
I have rolled back the change to the MAME lay file format. Hopefully this release corrects your issue.

Many thanks for reporting it.

**Comment by coolspot18** [comment]
Updated installer 1.12.1 fixed the issue. Thanks!
