### ISSUE TITLE
N64 bezel package doesn't work

### ISSUE THREAD

**Issue by conker-de** [thebezelproject/BezelProject-Windows#22]
Installing the n64 package on retropie with the bezel project script doesn't work properly because the usually added lines by the use of the script don't be added in the retroarch.cfg for n64. In opposite to the sense intended the .cfg-file will be cleared. In the consequence the n64 overlay settings is broken.

Thanks for this great work :-)

Edit: Tried with retropie 4.6 on rpi 4.

**Comment by thebezelproject** [comment]
Thanks for pointing that out. I have updated the script. Please run the update function to get the new version of the .sh file.
