### ISSUE TITLE
Mame issue on a 16:10 monitor

### ISSUE THREAD

**Issue by thonlorenz** [thebezelproject/BezelProject-Windows#26]
After downloading and implementing the mame bezels, mame is now displaying at a 16:9 aspect ratio on my 16:10 monitor. Is there a way to force mame to run at 16:10 while cropping or stretching the bezel artwork?

**Comment by thebezelproject** [comment]
Mame has a ton of video options (you can either edit the mame.ini directly, or hit the Tab key when in game to bring up the list of options). You will just have to try the different ways it has of giving you what you want.

**Comment by thonlorenz** [comment]
Thanks for the speedy reply. Here's what worked for me: 
In mame.ini, I set "artwork_crop" to 1

Thanks for the help, the great app and all the work it must take to make the bezels.

**Comment by leandromacrini** [comment]
I made a little python script that updates the viewport size and position to use the overlay on a 16:10 monitor -> https://github.com/leandromacrini/BEZEL-resizer

The overlay will justs fill the screen but it's not a big problem on a 16:10 screen, but now the viewport is the right size and in the correct position.
