### ISSUE TITLE
Andro Dunos bezel does'nt fits correctly displayed area.

### ISSUE THREAD

**Issue by Ferrulongu** [thebezelproject/BezelProject-Windows#27]
mame 0.235, Win 10

As in object, regards.

**Comment by thebezelproject** [comment]
My MAME 0.235 does not show this (see attachment), however you can modify the horizontal/vertical scale under the slider functions to get the affect you want.
![0000](https://user-images.githubusercontent.com/36973318/134574572-cf396f68-2df5-4098-a99c-8e1d6e6855b5.png)

**Comment by Ferrulongu** [comment]
Hi again. Noticed that in my distro all SNK/NEOGEO titles does the same; the green boot display fits perfectly, when all titles start there's half a cm black space on both right and left sides.

**Comment by thebezelproject** [comment]
That is very strange. Are you using the default build of MAME from mamedev.org? If so, do the older versions show the same output? I personally use the arcade64 build from https://arcade.mameworld.info/.

**Comment by Ferrulongu** [comment]
Yep, using official 0.235 from mamedev.org; I'll try a previous ver and let you know asap.

*EDIT* Everything's same with older or newer (just released 0.236) official rel from mamedev; all SNK/NEOGEO games don't fit the frame. 

*EDIT* to be more specific, all SNK/NeoGeo MVS games, not older ones (i.e. the first ASO, a SNK title, is ok with bezel).
