### ISSUE TITLE
MAME Layout view 'bezel artwork' contains deprecated bezel element

### ISSUE THREAD

**Issue by rromerob84** [thebezelproject/BezelProject-Windows#29]
As of version 0.225 of MAME, the layout files produce a warning in the Terminal, such as "Warning: layout view 'Upright_Artwork' contains deprecated bezel element."

**Comment by thebezelproject** [comment]
Yes, we are aware of the change. Unfortunately the majority of our audience still use an old version of MAME and require the original format. If you want to eliminate the warning, I would recommend mass editing the lay files with something like Notepad++ which can edit all the files in a couple of steps.

1. Change all instances of <bezel element= to <element ref=
2. Closing tags for all those should be <\/element>

Make sure you backup your MAME's artwork directory before the editing.

**Comment by SpiralBrad** [comment]
> "Change all instances of to"

Really now?

**Comment by thebezelproject** [comment]
> > "Change all instances of to"
> 
> Really now?

The original markup didn't translate. I have edited the text.
