### ISSUE TITLE
Bezel works only with USA roms can we help to expand?

### ISSUE THREAD

**Issue by xevious1974** [thebezelproject/BezelProject-Windows#34]
Bezel works only with USA roms can we help to expand?

I'd like to use bezel also with jap, eur, or other roms, using the same of USA
It is possibile?

**Comment by dragon57** [comment]
You don't say for which games or systems, but if you want to duplicate any existing cfg files under retroarch/config/<core_name>, then rename them to match the other non-US rom names, that will not cause any problem.

**Comment by xevious1974** [comment]
Dear Dragon, thank you very much for your reply! I have tried to change the config file and it works great!
Some times ago I have tried it but...do you know what I have changed? The name file in overlay folder...and so I was thinking that there was something coded in retroarch...
But now it works! Thank you again!!!
^_^
