### ISSUE TITLE
Incompatible with RetroArch on Steam

### ISSUE THREAD

**Issue by walchst** [thebezelproject/BezelProject-Windows#38]
For some odd reason this does not work with the Steam version of RetroArch. All the paths are relative, no hardcoating, and everything downloads to the right location. It's all processed correctly such that the bezels are associated with the roms, however they just do not appear when the content is being played.

**Comment by thebezelproject** [comment]
Thanks for the info. I'm not a RetroArch steam user, so was unaware. I'll try to test as soon as I can, but not sure when that will be. Will update here once I know more.

**Comment by thebezelproject** [comment]
I installed RetroArch in my Steam client today and followed up by installing a Bezel set. Everything works as expected here. Not sure what is going on with your installation. The only thing that comes to mind is a possible permissions issue. Where did you tell the Steam client to install Retroarch?

**Comment by walchst** [comment]
Interesting. Well that's promising. I've set up a separate drive (E:) in RetroArch as the default for all game installs. That results in the full path being "E:\SteamLibrary\steamapps\common\RetroArch". To rule out perms I've re-run Bezel Project as Admin, redownloaded and re-enabled but no change.

**Comment by thebezelproject** [comment]
Please provide me enough info so I can try to replicate here. What core are you using for what system. Give me a rom name or two you are trying to play where no bezel shows up (provide the full, exact rom name). Any other details you think would assist.

**Comment by walchst** [comment]
Not sure what went wrong here but got around to starting from scratch and this is all working as expected. Thanks for your help and confirmation that it was working from your side.
