### ISSUE TITLE
names don't always match no-intro datfiles

### ISSUE THREAD

**Issue by Kallin** [thebezelproject/BezelProject-Windows#4]
It looks like many of the files in the bezel project don't always line up with the latest datfiles from Nointro. In the guide it says files must be named using"No-Intro naming convention used by EmuMovies/HyperSpin."

For instance, looking at latest nointro datfile for megadrive, downloaded from datomatic, `Sega - Mega Drive - Genesis (20190620-073938).dat`, we quickly see a couple examples that don't line up with what's in bezel project:

datfile: `16t (Japan) (SegaNet)`
bezel_project: `16t (Japan)`

datfile: `Addams Family Values (Europe) (En,Fr,De)`
bezel_project: `Addams Family Values (Europe)`

There are many more examples across platforms. 

Here's a proposal (assuming I have correctly identified an issue here):

During the import process allow the user to point to their ROM directory so that the installer can actually see how files are named on a user's machine. Then for each rom, try to find a matching bezel using string similarity, or even just `string.startswith` after stripping out everything in brackets would probably cover most cases.

Love the project, thanks for all the great work!

**Comment by thebezelproject** [comment]
You are correct.

As a bit of background, this project started, and continues to be first and foremost related to the RetroPie platform and a specific build which contains a specific rom set. At the time of the creation of the set, the names should have been correct.

As we move in the future, more and more bezel sets that don't have direct ties to the original set will have more up to date No-Intro names, but as I am sure you are aware, even the No-Intro databases can modify names along the way, so naming is always a moving target.

Having said all of that, the project hasn't even finished its first pass at creating bezels for most systems. Once that is done, I am sure the sets will be fleshed out with more bezel support for naming other than North American. Some already contain some EU and Japanese named bezels, but not many. Names will be updated as well at some time in the future as time permits.

In the mean time, I recommend you get comfortable with your bulk renaming utility of choice. ;)

**Comment by Kallin** [comment]
Thanks for the prompt reply! I will see if I can write a little script to tide me over for now.

What do you think of the approach of not tying the bezels to individual versions necessarily? As an example, Alien 3 on the SNES currently has 7 roms across regions and versions. Do we really need 7 different images? I'd personally be happy having just 1 in the git project, and then have the bezel project installer just create 7 copies after reading my roms directory.

I suppose another tactic would be to lobby retroarch to enhance their overlay feature to not be so strict on naming.

**Comment by thebezelproject** [comment]
Since we are depending on Retroarch on most of the different platforms we support, MAME, RetroPie, Windows, PSP, Switch, Vita, we are tied to how it implements its override system, which is how we are structured, we must tie the bezel names to the rom names.

**Comment by Kallin** [comment]
Right, so using Alien 3 on SNES as an example, at present bezel project has `Alien 3 (USA).cfg` , which contains:

```
overlays = 1

overlay0_overlay = ":/overlays/GameBezels/SNES/Alien 3 (USA).png"

overlay0_full_screen = true

overlay0_descs = 0
```

along with a corresponding `Alien 3 (USA).png`.

What if, instead of that we just store `Alien 3.png` and no CFG file in the repository, then at install time, we copy over the PNG, and generate as many CFG files as necessary, based on the ROMs that are available. So, with latest no-intro set, you'd generate:

```
Alien 3 (Japan).cfg
Alien 3 (USA) (Beta 1).cfg
Alien 3 (USA) (Beta 2).cfg
Alien 3 (USA) (Beta 2).cfg
Alien 3 (USA) (Beta 3).cfg
Alien 3 (USA) (Rev 1).cfg
Alien 3 (USA).cfg
```

And they would all have the same content:

```
overlays = 1

overlay0_overlay = ":/overlays/GameBezels/SNES/Alien 3.png"

overlay0_full_screen = true

overlay0_descs = 0
```

Seems like a future proof solution.

**Comment by thebezelproject** [comment]
You still would create a situation where many would not have their games named correctly according to what the script would expect. Since we aren't in the business of distributing rom packs, the variations that are available can cause chaos for those that aren't coders, or are comfortable doing a lot of file name manipulations.

**Comment by Kallin** [comment]
In the project's description it says that you must use the "No-Intro" naming convention. Of course you cannot enforce that user's will name their roms correctly, but if you assume they are something like the no-intro conventions, you could immediately have much better coverage and have a much more effective tool for many more users for a minimal amount of work. Not sure why you would close so quickly. How is having the file names locked to a random historical version of one romset better than having a future proof solution that would work for most everything?

**Comment by CoinJunkie** [comment]
If anyone would like to contribute in our group with solutions for discussions with many of us we'd love to have in our home base the Facebook group and chat there. 

https://www.facebook.com/groups/807426606027897/
