### ISSUE TITLE
N64 Bezels Won't Autoconfig

### ISSUE THREAD

**Issue by OfficePop** [thebezelproject/BezelProject-Windows#4]
I am having trouble getting the N64 bezels to configure with my games after running the installer. I notice that it unpacks the configs into a folder for "Mupen64Plus GLES2", but Retroarch only offers the Mupen64PlusNext core.

**Comment by thebezelproject** [comment]
Looks like the Libretro people have made another core name change. Feel free to just rename that directory under config to match the name the core requires. Everything should work after that.

**Comment by donaleo** [comment]
Sorry to reopen this almost year-old question. I am having the same problem. And I am currently scouring the web looking for some kind of visual guide in order to "rename that directory under config to match the name the core requires". This thread seems to be the most detailed and I am trying to figure out where the folder even is that needs to be renamed. Retro arch has lots of config files and I am not sure which one to alter.

**Comment by thebezelproject** [comment]
This refers to the config directory under the retroarch install directory. Inside of config, there will be subdirectories named to match the internal retroarch core names. Depending on which version of the core files you are using, those names may differ than what we used upon bezel creation. You just rename those to match whatever name your particular core requires. The easiest way to figure that out is to load up a game under the core in question, pop back into retroarch by pressing F1, then make some change and save a core override file. Exit and look under config to see where that core override was saved. If it was saved into an existing subdirectory, the issue isn't the subdirectory name, but more than likely your rom names. If the override file was saved to a new directory, not the new name, delete this new directory, then rename the old one to match the new name. Test and see if the bezels show up. If not, the rom names could still be the issue. If this info doesn't help you, your best bet is to ask questions on the libretro forums.

**Comment by donaleo** [comment]
I did not expect such a prompt reply but I appreciate it! Your response was also highly informative, I really appreciate you being so generous with your knowledge. I will try this when I get home and will report back to let you know how it goes! Thanks again!

**Comment by donaleo** [comment]
It worked it worked!!! That was a lot easier than i thought. All you need is a little know-how guidance from a veteran in this scene. Thanks again!
