### ISSUE TITLE
Sega Megadrive (Genesis) not recognized

### ISSUE THREAD

**Issue by stzokev** [thebezelproject/BezelProject-Windows#5]
Just installed the bezel_project_web_installer_v1.5.exe and selected RetroArch -> Mame and Sega MegaDrive as I have only these platforms at the moment. I am using Launchbox as my front end. For the Mame games the bezels are correctly found and working great. However none of the Sega Genesis game have bezels applied for them. I have tried launching directly from RetroArch and still no bezels. When I check the RetroArch\overlays\GameBezels\Megadrive folder, I can see all the bezels are there. What configuration am I missing?

**Comment by stzokev** [comment]
Today I've tried clean install of RetroArch and Bezels project on a different machine and got the same problem. Basically I've just installed RetroArch and Bezel project and haven't changed any settings whatsoever (everything default).

**Comment by thebezelproject** [comment]
Currently Megadrive is configured to support the Genesis Plus GX and PicoDrive core names. If you are using a different core, or the core name is different than these two, just rename one of the directories under config and the core you are using should recognize the files.

**Comment by stzokev** [comment]
I am using Genesis Plus core, its default name is genesis_plus_gx_libretro.dll What directory folder should I rename?

**Comment by thebezelproject** [comment]
The Genesis Plus GX core support directory is already there, like I alluded to earlier, so you shouldn't have to rename it.

Have you confirmed your game file names match the cfg files in the Genesis Plus GX directory under the "config\Genesis Plus GX" directory for Retroarch?

**Comment by stzokev** [comment]
That was it! I've gathered my collections for many years, so the names were absolutely different. But it would have never occurred to me that this is the problem, as Launchbox didn't have any problems scraping images for them i.e. Launchbox managed to identify which rom is which, so I expected similar way of identifying. Apparently MAME roms work with the bezel project, as their names cannot be edited or games do not work.

Thank you!
