### ISSUE TITLE
1942 NES Bezel Keeps Showing Up on the Wrong Games

### ISSUE THREAD

**Issue by 9dodge88** [thebezelproject/BezelProject-Windows#6]
I believe I’m having the same problem as the user below. 1942 NES keeps showing up on my other games. Some games show the right one, but more times than not it’s always 1942 NES. What can I try???

**Comment by thebezelproject** [comment]
It sounds like you have the 'save configuration on exit' set to true in Retroarch. Change this to false, save the configuration, then exit Retroarch. Manually edit the retroarch.cfg and remove the reference to the 1942 cfg file.

**Comment by 9dodge88** [comment]
That fixed it. Thank you. Now I have to figure out why the TG16, Atari 2600, & SNES bezels won’t load at all.

**Comment by thebezelproject** [comment]
Common issues to bezels not loading is naming differences of either your rom sets, or the core config directory name in the Retroarch config directory not matching the core you are using.

**Comment by 9dodge88** [comment]
One more quick question.  If I just want to use the stock bezel for each system.  Where do I need to put the cfg file and png file in retroarch for it to pull them?  For instance if I just want to use the Atari-2600.png file for all my 2600 games where do I put those files?  Thanks.

Joel T. Hill
Materials Center Manager, AMSTI-AU
1900 Cunningham Drive
Opelika, Alabama 36801
(334) 737-5012
jth0008@auburn.edu<mailto:jth0008@auburn.edu>





On Nov 26, 2019, at 10:12 PM, The Bezel Project <notifications@github.com<mailto:notifications@github.com>> wrote:


Common issues to bezels not loading is naming differences of either your rom sets, or the core config directory name in the Retroarch config directory not matching the core you are using.

**Comment by thebezelproject** [comment]
You don't need to move the cfg and png from the overlays directory. If you want to use the default for all games in a platform, you would need to delete all the installed files from the GameBezels/Arcadebezels directories, then create a core override for the platform which has the appropriate default bezel selected.
