### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by Reudaisu** [thebezelproject/BezelProject-Windows#7]
Hi there, 

I installed the bezel project on RetroArch running through LaunchBox

How do I automatically uninstall or manually remove the bezels after installing them?

**Comment by thebezelproject** [comment]
If you are using the latest version of the Windows installer, it should give you the option of uninstalling each bezel set you have installed. If you need specific steps for a manual clean up, please let us know.

**Comment by Reudaisu** [comment]
> If you are using the latest version of the Windows installer, it should give you the option of uninstalling each bezel set you have installed. If you need specific steps for a manual clean up, please let us know.

Actually yeah, I would rather have the steps of manually cleaning up.

**Comment by thebezelproject** [comment]
The base cfg files that point to the bezel sets can be found in the <retroarch install folder>\config\<core name> directories. Remove all the cfg files that match your rom names from that directory. The actual end point cfg and png files can be found in the <retroarch install folder>\overlays\Gamebezels\<system name> directories. Remove the directory that matches the system you want to clean up.
