### ISSUE TITLE
Software will not locate MAME installation...

### ISSUE THREAD

**Issue by edunbarr** [thebezelproject/BezelProject-Windows#8]
...even though I've installed MAME64 in my LaunchBox directory. I've pointed the program at the MAME folder, but when I get to the Download Bezel section it tells me that MAME isn't installed. Have I goofed something up?

See, it's installed...
![file](https://user-images.githubusercontent.com/60379810/73241977-e7369000-4160-11ea-9bf0-476f65d48203.PNG)

And I've pointed BP at the folder...
![location](https://user-images.githubusercontent.com/60379810/73242002-f584ac00-4160-11ea-8a90-a2c1fd76bba8.PNG)

But this is what it keeps telling me...
![issue](https://user-images.githubusercontent.com/60379810/73242007-fb7a8d00-4160-11ea-84ee-8412ee883e90.PNG)

**Comment by dougsky** [comment]
what he mentions is not installed are the bezels!!!!

**Comment by thebezelproject** [comment]
dougsky is correct. The statement from the installer refers to the state of bezel installation, not that MAME isn't installed.

**Comment by edunbarr** [comment]
Ohhh, so it's not asking me to install MAME, the bottom option is just telling me that it's ready to install MAME's _bezels_. Thank you both for your clarification!
